### ISSUE TITLE
findAll not running recursively

### ISSUE THREAD

**Issue by oisinlavery** [figma-plugin-helper-functions/figma-plugin-helpers#59]
test file: https://www.figma.com/file/sidppHshZlzQ9UM1TAfgcC/findAll-test?node-id=0%3A1

`findAll(figma.currentPage.children, node => true)`
returns 2 nodes

`figma.currentPage.findAll(node => true)`
returns 7 elements (the number of nodes in the file)

<img width="1842" alt="Screen Shot 2020-07-15 at 7 59 44 PM" src="https://user-images.githubusercontent.com/1757344/87584781-eb864380-c6d5-11ea-970c-7bb62cc13687.png">

**Comment by alexandrtovmach** [comment]
I found where is the problem is, but also I figured out that we shouldn't use this custom method:
![image](https://user-images.githubusercontent.com/28801003/87634375-c8937800-c745-11ea-8eec-ad64b7b16a47.png)


Figma team patched their `findAll` realization, and now it's faster than custom. There are no clear way to install previous version of Figma, to find where this update was, but from release log I can suggest this version:
https://releases.figma.com/2020/04/figma-desktop-app-beta-8610.html

I'm going to deprecate this method, and switch back to native `findAll`.

**Comment by oisinlavery** [comment]
Thanks for investigating this Alex. Maybe this method inspired Figma to improve theirs :)
